config/routes.rb
Rails.application.routes.draw do
  devise_for :organizations, controllers: {
    sessions: 'organizations/sessions',
    registrations: 'organizations/registrations'
  }
  devise_for :users, controllers: {
    invitations: 'users/invitations',
    sessions: 'users/sessions'
  }

  root 'pages#home'
  
  get 'pages/about', to: 'pages#about'
  get 'pages/plans', to: 'pages#plans'
  get 'pages/dashboard', to: 'pages#dashboard'
  get 'upgrade_plan', to: 'pages#edit_plan'
  patch 'upgrade_plan', to: 'pages#upgrade_plan'
  put 'upgrade_plan', to: 'pages#upgrade_plan'

  post 'payments/create-intent', to: 'payments#create_intent'

  post 'validations/organization', to: 'validations#organization_valid?'

  # post 'projects/withdraw_user', to: 'projects#withdraw_user'
  # post 'projects/assign_user', to: 'projects#assign_user'
  resources :projects do
    get '/manage', to: 'projects#manage_team'
    post '/withdraw_user', to: 'projects#withdraw_user'
    post '/assign_user', to: 'projects#assign_user'
  end

  resources :artifacts
end

app/views/pages/about.html.erb
<div class='w-100 d-flex flex-column justify-content-center align-items-center'>
  <h3 class="h3 text-danger">About application:</h3>
  <p class='lead h4'>This application created as education project by Igor Slepenkov.</p>
  <p class='lead h4'>Technologies used:</p>
  <ul class='w-50 list-group'>
    <li class='list-group-item'>Ruby on Rails</li>
    <li class='list-group-item'>Devise + Devise invitable</li>
    <li class='list-group-item'>Carrierwave + Fog/Google</li>
    <li class='list-group-item'>Payment: Stripe</li>
    <li class='list-group-item'>Database: Postgresql</li>
    <li class='list-group-item'>Styling: Bootstrap + custom</li>
  </ul>
</div>

app/views/pages/dashboard.html.erb
<div class="w-100 d-flex flex-column align-items-center">
  <h2 class="h2 mt-5">Welcome to Dashboard</h3>
  <div class="org-dashboard container contianer-fluid text-center">
    <div class="org-controllers d-flex justify-content-between">
      <%= link_to "Invite new user", new_user_invitation_path, class: "btn btn-light" %>
      <% unless current_organization.plan == 'free' && !current_organization.projects.empty? %>
        <%= link_to "New project", new_project_path, class: "btn btn-light" %>
      <% end %>
    </div>
    <div class="org-info">
      <h3 class="h3">Organization Info:</h3>
      <ul class="list-group text-start">
        <li class="list-group-item list-group-item-dark">Name: <%= @organization.name %></li>
        <li class="list-group-item list-group-item-light">Email: <%= @organization.email %></li>
        <li class="list-group-item list-group-item-dark">Plan: <%= @organization.plan.upcase %></li>
        <li class="list-group-item list-group-item-light">Domain: <%= @domain %></li>
      </ul>
    </div>
    <div class="org-workers mt-5">
      <h3 class="h3">Invited Workers:</h3>
      <% if @organization.users.any? %>
        <table class="table table-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">First name</th>
            <th scope="col">Last name</th>
            <th scope="col">Email</th>
          </tr>
          <% @organization.users.each_with_index do |user, idx| %>
            <tr>
              <th scope="row"><%= idx + 1 %></th>
              <td><%= user.first_name %></td>
              <td><%= user.last_name %></td>
              <td><%= user.email %></td>
            </tr>
          <% end %>
        </table>
      <% end %>
    </div>
    <div class="org-projects">
      <h3 class="h3">Your projects:</h3>
      <%= render 'projects/list', list: @projects %>
    </div>
  </div>
</div>

app/views/pages/edit_plan.html.erb
<div class="w-100 d-flex flex-column justify-content-center align-items-center">
  <h2>Upgrade to premium</h2>
  <%= form_with model: @organization, url: upgrade_plan_path, class: 'w-75', html: {id: 'payment-form-update'} do |f| %>
    <div class="org-payment field">
      <div id="payment-element">
        <!--Stripe.js injects the Payment Element-->
      </div>
      <div id="payment-message" class="hidden"></div>
    </div>
    <%= f.hidden_field :payment %>
    <%= f.submit 'Pay and upgrade', class: "btn btn-light btn-lg mt-3", id: 'submit_btn' %>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="w-100 d-flex flex-column justify-content-center align-items-center">
  <h2 class="h2">Welcome to Management App!</h3>
  <p class="h3 mb-3">We are glad to see you on our home page!</p>
  <% if current_organization %>
    <p class="lead h3">Go to your organization's dashboard</p>
    <%= link_to "Dashboard", pages_dashboard_path, class: "btn btn-lg btn-light" %>
  <% elsif current_user %>
    <p class='lead h3'>Use the link below to naviate to your projects</p>
    <%= link_to 'My Projects', projects_path, class: 'btn btn-lg btn-light' %>
  <% else %>
    <p class="lead">In order to continue using application, please pass a registration or sign in</p>
    <%= link_to "Sign In", new_organization_session_path, class: "btn btn-lg btn-light" %>
    or 
    <%= link_to "Take a look at plans", pages_plans_path, class: "btn btn-lg btn-light" %>
  <% end %>
</div>

app/views/pages/index.html.erb
<h1 class="text-danger"> Hello world </h1>

app/views/pages/plans.html.erb
<div class="w-100 d-flex flex-column justify-content-center align-items-center">
  <h2 class="h2">Take a closer look at our plans</h3>
  <div class="d-flex mt-3">
    <div class="card text-bg-secondary me-3" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">Free Plan</h5>
        <ul class="list-group list-group-flush text-start rounded mb-2 mt-2">
          <li class="list-group-item">Unlimited file uploads</li>
          <li class="list-group-item">Responsive design</li>
          <li class="list-group-item">Access anywhere</li>
          <li class="list-group-item">1 project</li>
        </ul>
        <p class="lead">FOR FREE</p>
        <%= link_to "Sign Up", new_organization_registration_path, class: "btn btn-light" %>
      </div>
    </div>
    <div class="card text-bg-secondary" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">Premium Plan</h5>
        <ul class="list-group list-group-flush text-start rounded mb-2 mt-2">
          <li class="list-group-item">Unlimited file uploads</li>
          <li class="list-group-item">Responsive design</li>
          <li class="list-group-item">Access anywhere</li>
          <li class="list-group-item">Unlimited amount of projects</li>
        </ul>
        <p class="lead">Price: 10$</p>
        <%= link_to "Sign Up", new_organization_registration_path, class: "btn btn-light" %>
      </div>
    </div>
  </div>
</div>