config/routes.rb
Rails.application.routes.draw do
  devise_for :organizations, controllers: {
    sessions: 'organizations/sessions',
    registrations: 'organizations/registrations'
  }
  devise_for :users, controllers: {
    invitations: 'users/invitations',
    sessions: 'users/sessions'
  }

  root 'pages#home'
  
  get 'pages/about', to: 'pages#about'
  get 'pages/plans', to: 'pages#plans'
  get 'pages/dashboard', to: 'pages#dashboard'
  get 'upgrade_plan', to: 'pages#edit_plan'
  patch 'upgrade_plan', to: 'pages#upgrade_plan'
  put 'upgrade_plan', to: 'pages#upgrade_plan'

  post 'payments/create-intent', to: 'payments#create_intent'

  post 'validations/organization', to: 'validations#organization_valid?'

  # post 'projects/withdraw_user', to: 'projects#withdraw_user'
  # post 'projects/assign_user', to: 'projects#assign_user'
  resources :projects do
    get '/manage', to: 'projects#manage_team'
    post '/withdraw_user', to: 'projects#withdraw_user'
    post '/assign_user', to: 'projects#assign_user'
  end

  resources :artifacts
end

app/models/project.rb
class Project < ApplicationRecord
  acts_as_tenant :organization
  has_many :artifacts, dependent: :destroy
  has_and_belongs_to_many :users
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :authenticate_organization!, only: %i[index show]
  skip_before_action :authenticate_user!, except: %i[index]
  before_action :initialize_project, except: %i[index new create manage_team assign_user withdraw_user]

  def index
    @projects = current_user.projects
  end

  def show; end

  def new; end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to pages_dashboard_path, notice: 'Project has been successfully created'
    else
      render 'new', status: :bad_request
    end
  end

  def edit; end

  def update
    if @project.update(project_params)
      redirect_to pages_dashboard_path, notice: 'Project has been updated'
    else
      render 'edit', status: :bad_request
    end
  end

  def destroy
    @project.destroy
    redirect_to pages_dashboard_path, notice: 'Project has been successfully destroyed'
  end

  def manage_team
    @project = Project.find(params.require(:project_id))
    @users_to_assign = current_organization.users.filter { |user| !@project.users.include?(user) }
  end

  def assign_user
    @project = Project.find(params.require(:project_id))
    @user = User.find(params.require(:project_user))
    @project.users << @user
    redirect_to project_path(@project), notice: 'User assigned successfully'
  end

  # def withdraw_user
  #   withdraw_user_id = params
  #   filtered_users = @project.users.filter { |user| user.id != id }
  #   @project.users = filtered_users
  #   redirect_to project_path(@project), notice: 'User withdrawed successfully'
  # end

  private

  def project_params
    params.require(:project).permit(:title, :details, :expected_completion_date)
  end

  def initialize_project
    @project = Project.find(params[:id])
  end
end

app/views/projects/_form.html.erb
<% f = locals[:f] %>
<div class="field">
  <%= f.label :title, class: "lead"  %><br />
  <%= f.text_field :title, autofocus: true, class: "form-control"  %>
</div>
<div class="field">
  <%= f.label :details, class: "lead"  %><br />
  <%= f.text_area :details, class: "form-control"  %>
</div>
<div class="field">
  <%= f.label :expected_completion_date, class: "lead" %><br />
  <div class="input-group">
    <%= f.date_select :expected_completion_date, {}, {class: "form-select"} %>
  </div>
</div>
<div class="org-submit actions d-flex flex-column">
  <em class="text-danger mb-2 mt-2">all fields are requred</em>
  <%= f.submit "Submit", class: "btn btn-light btn-lg mb-3"  %>
</div>

app/views/projects/_list.html.erb
<% if list && !list.empty? %>
  <table class="table table-light table-striped">
    <tr>
      <th scope="row">#</th>
      <th scope="col"> Title </th>
      <th scope="col"> Details </th>
      <th scope="col"> Expected completion </th>
      <th colspan="2">Actions</th>
    </tr>
    <% list.each_with_index do |project, idx| %>
      <tr>
        <td scope="row"> <%= idx + 1 %> </td>
        <td> <%= link_to project.title, project_path(project) %> </td>
        <td> <%= project.details %> </td>
        <td> <%= project.expected_completion_date %> </td>
        <td><%= link_to "Destroy", 
                project_path(project), 
                data: {turbo_method: :delete},
                class: "btn btn-danger" %></td>
        <td><%= link_to "Edit", 
                edit_project_path(project),
                class: "btn btn-info"%></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <div class="d-flex flex-column align-items-center mb-5">
    <h3 class="h3 text-info">You don't have any projects yet</h3>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="w-100 d-flex flex-column align-items-center justify-content-center">
  <h3 class="h3 mb-3">Create your new project</h3>
  <%= form_with model: @project, url: project_path(@project), data: {turbo_method: :put} do |form| %>
    <%= render 'form', locals: {f: form} %>
  <% end %>
</div>

app/views/projects/index.html.erb
<div class="w-100 d-flex flex-column align-items-center justify-content-center">
  <h3 class="h3 mb-3">You involved in next projects:</h3>
  <% if @projects %>
    <table class="w-50 table table-light table-striped">
      <tr>
        <th scope="row">#</th>
        <th scope="col"> Title </th>
        <th scope="col"> Details </th>
        <th scope="col"> Expected completion </th>
      </tr>
      <% @projects.each_with_index do |project, idx| %>
        <tr>
          <td scope="row"> <%= idx + 1 %> </td>
          <td> <%= link_to project.title, project_path(project) %> </td>
          <td> <%= project.details %> </td>
          <td> <%= project.expected_completion_date %> </td>
        </tr>
      <% end %>
    </table>
  <% else %>
    <div class="d-flex flex-column align-items-center mb-5">
      <h3 class="h3 text-info">You don't have any projects yet</h3>
    </div>
  <% end %>
</div>

app/views/projects/manage_team.html.erb
<div class="w-100 d-flex flex-column align-items-center justify-content-center">
  <h3 class="h3 mb-3">Manage your project's team</h3>
  <div class='mb-3'>
    <h4 class='h4'>Current project's team:</h4>
    <% if @project.users.any? %>
      <div class="table-responsive">
        <table class="table table-light text-center">
          <tr>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Email</th>
            <th scope="col">Project's IDs</th>
            <th scope="col">Actions</th>
          </tr>
          <% @project.users.each do |user| %>
            <tr>
              <td><%= user.first_name %></td>
              <td><%= user.last_name %></td>
              <td><%= user.email %></td>
              <td><%= user.projects.map { |project| project.id }.join(', ') %></td>
              <td><%= link_to 'Withdraw', project_withdraw_user_path, class: 'btn btn-danger' %></td>
            </tr>
          <% end %>
        </table>
      </div>
    <% else %>
      <h5 class='h5 text-info'>You don't have assigned users in this project yet</h5>
    <% end %>
  </div>
  <div class='mb-3'>
    <h4 class='h4'>Assign new user to the project:</h4>
    <% if @users_to_assign.any? %>
      <%= form_with url: project_assign_user_path, method: :post do |form| %>
        <select name="project_user" id="project_user" class='form-control'>
          <%= @users_to_assign.each do |user| %>
            <option value="<%= user.id %>"><%= user.first_name + ' ' + user.last_name %></option>
          <% end %>
        </select>
        <%= form.submit 'Assign user', class: 'btn btn-light mt-3' %>
      <% end %>
    <% else %>
      <h5 class='h5 text-info'>All your users allready work on this project</h5>
    <% end %>
  </div>
  <%= link_to 'Back to project', project_path(@project), class: 'btn btn-primary' %>
</div>

app/views/projects/new.html.erb
<div class="w-100 d-flex flex-column align-items-center justify-content-center">
  <h3 class="h3 mb-3">Create your new project</h3>
  <%= form_with scope: :project, url: projects_path, data: {turbo_method: :post} do |form| %>
    <%= render 'form', locals: {f: form} %>
  <% end %>
</div>

app/views/projects/show.html.erb
<div class="w-100 d-flex flex-column align-items-center justify-content-center">
  <div class="w-50 card text-bg-light border-light" style="width: 18rem;">
    <h5 class="card-header">Project <%= @project.id %></h5>
    <div class="card-body text-start">
      <h6 class="card-title">Title: <%= @project.title %></h6>
      <p class="card-text mt-4 mb-4">Details: <%= @project.details %></p>
      <p class="card-text">Expected completion: <%= @project.expected_completion_date %></p>
      <% if @project.artifacts.any? %>
        <p class="card-text text-center">Artifacts:</p>
        <div class="table-responsive">
          <table class="table table-dark text-center">
            <tr>
              <th>Name</th>
              <th>Key</th>
              <th>Actions</th>
            </tr>
            <% @project.artifacts.each do |artifact| %>
              <tr>
                <td><%= artifact.name %></td>
                <td><a href="<%=artifact.key %>" target="_blank">Link</a></td>
                <td><%= link_to 'Destroy', 
                        artifact_path(artifact), 
                        class: 'btn btn-danger', 
                        data: {turbo_method: :delete} %></td>
              </tr>
            <% end %>
          </table>
        </div>
      <% end %>
    </div>
    <div class="card-footer">
      <% if organization_signed_in? %>
        <%= link_to "Destroy project", project_path(@project), class: "btn btn-danger" %>
        <%= link_to "Edit project", edit_project_path(@project), class: "btn btn-info" %>
        <%= link_to 'Manage project\'s team', project_manage_path(@project), class: 'btn btn-dark' %>
      <% end %>
      <%= link_to "Add Artifact", new_artifact_path + "?project_id=#{@project.id}", class: "btn btn-dark" %>
    </div>
  </div>
</div>