config/routes.rb
Rails.application.routes.draw do
  devise_for :organizations, controllers: {
    sessions: 'organizations/sessions',
    registrations: 'organizations/registrations'
  }
  devise_for :users, controllers: {
    invitations: 'users/invitations',
    sessions: 'users/sessions'
  }

  root 'pages#home'
  
  get 'pages/about', to: 'pages#about'
  get 'pages/plans', to: 'pages#plans'
  get 'pages/dashboard', to: 'pages#dashboard'
  get 'upgrade_plan', to: 'pages#edit_plan'
  patch 'upgrade_plan', to: 'pages#upgrade_plan'
  put 'upgrade_plan', to: 'pages#upgrade_plan'

  post 'payments/create-intent', to: 'payments#create_intent'

  post 'validations/organization', to: 'validations#organization_valid?'

  # post 'projects/withdraw_user', to: 'projects#withdraw_user'
  # post 'projects/assign_user', to: 'projects#assign_user'
  resources :projects do
    get '/manage', to: 'projects#manage_team'
    post '/withdraw_user', to: 'projects#withdraw_user'
    post '/assign_user', to: 'projects#assign_user'
  end

  resources :artifacts
end

app/views/layouts/_footer.html.erb
<footer class="border-top border-light mt-3">
  <p class="text-light">Management App</p>
  <p class="text-secondary">@ All rights reserved by management app team</p>
</footer>

app/views/layouts/_header.html.erb
<header class="border-bottom border-light mb-3">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid d-flex align-items-center">
      <a class="navbar-brand" href="<%= root_path %>">Management App</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="<%= pages_about_path %>">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= pages_plans_path %>">Plans</a>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'My projects', projects_path, class: 'btn bg-info bg-gradient ms-3' %>
            </li>
          <% end %>
          <% if organization_signed_in? %>
            <li class="nav-item">
              <a class="nav-link" href="<%= pages_dashboard_path %>">Dashboard</a>
            </li>
          <% end %>
          <% if organization_signed_in? && current_organization.plan == 'free' %>
            <li class="nav-item">
              <%= link_to 'Upgrade to premium', upgrade_plan_path, class: 'btn bg-success bg-gradient ms-3' %>
            </li>
          <% end %>
        </ul>
      </div>
      <% if organization_signed_in? && user_signed_in? %>
        <div class="dropdown">
          <%= link_to 'Sign Out (from all acounts)', 
              destroy_organization_session_path, 
              class: "btn btn-danger", 
              data: {turbo_method: :delete} %>
        </div>
      <% elsif user_signed_in? %>
        <div>
          <%= link_to 'Sign in as organization', new_organization_session_path, class: "btn btn-light"%>
          <%= link_to current_user.first_name, edit_user_registration_path, class: "btn btn-light me-3" %>
          <%= link_to 'Sign Out', destroy_user_session_path, class: "btn btn-danger", data: {turbo_method: :delete} %>
        </div>
      <% elsif organization_signed_in? %>
        <div>
          <%= link_to 'Sign in as worker', new_user_session_path, class: "btn btn-light"%>
          <%= link_to current_organization.name, edit_organization_registration_path, class: "btn btn-light me-3" %>
          <%= link_to 'Sign Out', destroy_organization_session_path, class: "btn btn-danger", data: {turbo_method: :delete} %>
        </div>
      <% else %>
        <div class="dropdown">
          <button class="btn btn-light dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Sign In
          </button>
          <ul class="dropdown-menu">
            <li><%= link_to 'As organization', new_organization_session_path , class: "dropdown-item"%></li>
            <li><%= link_to 'As worker', new_user_session_path , class: "dropdown-item"%></li>
          </ul>
        </div>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/_messages.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <strong><%= flash[:alert] %></strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong><%= flash[:notice] %></strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/layouts/_redirect.html.erb
<div class="alert alert-info alert-dismissible fade show" role="alert">
  <p class="lead">You have been redirected because you didn't use you own application domain</p>
  <p>Now, when you are on your working subdomain you may login and continue to use it</p>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
  </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails SaaS Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://js.stripe.com/v3/" defer></script>
    <%= javascript_include_tag 'stripe', defer: true%>
    <%= javascript_include_tag 'stripe_update_form', defer: true%>
  </head>
  <body class="container d-flex flex-column min-vh-100 text-center text-white bg-dark">
    <%= render 'layouts/header' %>
    <%= render 'layouts/messages' %>
    <%= render 'layouts/redirect' if redirected? && !organization_signed_in? %>
    <main class="flex-grow-1 d-flex align-items-stretch">
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>